name: blueprints

on:
  push:
    branches:
      - dev-compose
  pull_request:
    branches:
      - dev-compose

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Build project Mock and UnitTest
        run: ./gradlew assembleMockDebug assembleProdDebug compileMockDebugUnitTestKotlin

      - name: Spotless
        run: ./gradlew spotlessCheck

      - name: Robolectric Mock
        run: ./gradlew testMockDebugUnitTest

      - name: Build project Prod and UnitTest
        run: ./gradlew assembleMockDebug assembleProdDebug compileProdDebugUnitTestKotlin

      - name: Robolectric Prod
        run: ./gradlew spotlessCheck assembleMockDebug assembleProdDebug testMockDebugUnitTest testProdDebugUnitTest --stacktrace

#  test:
#    needs: build
#    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
#    timeout-minutes: 30
#    strategy:
#      matrix:
#        api-level: [23, 29]
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Copy CI gradle.properties
#        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#

#
#      - name: Upload test reports
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-reports
#          path: app/build/reports/

#
#  gradleManagedVirtualDevicesTest:
#    needs: build
#    runs-on: macos-latest
#    timeout-minutes: 30
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Copy CI gradle.properties
#        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11

      # Needed to accept licenses
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

#      - name: Generate cache key for Gradle cache
#        run: ./scripts/checksum.sh $SAMPLE_PATH checksum.txt
#
#      - uses: actions/cache@v2
#        with:
#          path: |
#            ~/.gradle/caches/modules-*
#            ~/.gradle/caches/jars-*
#            ~/.gradle/caches/build-cache-*
#          key: gradle-${{ hashFiles('checksum.txt') }}

#      - name: Cache pixel2api30 system image
#        uses: actions/cache@v2
#        with:
#          path: |
#            ~/.android/gradle/avd/dev30_aosp-atd_x86_Pixel_2.avd.*
#          key: pixel2api30
#
#      - name: Cache pixel2api27 system image
#        uses: actions/cache@v2
#        with:
#          path: ~/.android/gradle/avd/dev27_aosp_x86_Pixel_2.*
#          key: pixel2api27
#
#      - name: Cache nexus9api29 system image
#        uses: actions/cache@v2
#        with:
#          path: ~/.android/gradle/avd/dev29_aosp_x86_Nexus_9.*
#          key: nexus9api29

#      - name: Run all tests pixel 2 api 27 ATD
#        working-directory: ${{ env.SAMPLE_PATH }}
#        run: ./gradlew pixel2api27atdMockDebugAndroidTest
#
#      - name: Run all tests nexus 9 api 29 ATD
#        working-directory: ${{ env.SAMPLE_PATH }}
#        run: ./gradlew nexus9api29atdMockDebugAndroidTest

      - name: Compile AndroidTests Mock
        run: ./gradlew compileMockDebugAndroidTestKotlin

      - name: Run all tests pixel 2 api 30 ATD
        working-directory: .
        run: ./gradlew -Pandroid.sdk.channel=3 -Pandroid.experimental.androidTest.numManagedDeviceShards=1 -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" pixel2api30atdMockDebugAndroidTest

      - name: Run instrumentation tests API 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86
          disable-animations: true
          script: ./gradlew app:cMDAT --stacktrace

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: app/build/reports/

      - name: Upload all outputs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: app/build/outputs/

#      - name: Upload test reports
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-reports
#          path: ./app/build/reports/androidTests/managedDevice/
